### ISSUE TITLE
Audio Indicator

### ISSUE THREAD

**Issue by pragmatech** [miroslavpejic85/mirotalkc2c#1]
Kudos on a simplified and exceptional way to do this! To me anyway, a mesh approach feels a lot better than wrestling with a SFU and the rest. Particularly in terms of audio-only connections, it would be great to have access to the magic sauce of the speaker's audio signal lighting like in mirotalk, or better yet, in the clubhouse fashion. As you have kept it in vanilla js maybe I can figure it out. Any pointers are much appreciated. Thanks for sharing your fine work!

**Comment by miroslavpejic85** [comment]
Hi @pragmatech, It's my pleasure to share it.
Regarding the audio indicator as in [MiroTalk P2P](https://github.com/miroslavpejic85/mirotalk), i think here not have sense to have it as it is Cam-2-Cam video calls. IMHO, It have sense for a large group meetings, in order to know who speaking in the room. The intention of MiroTalk C2C project, is to make it as simple as possible, for the scope it is created ;)
