### ISSUE TITLE
iOS and Firefox - GetUserMedia Error

### ISSUE THREAD

**Issue by torrswanson** [miroslavpejic85/mirotalkc2c#12]
**Error**
- I noticed on iOS c2c.mirotalk.com that the GetUserMedia request fails and causes an error. And never requests camera or microphone permissions. The browser is not aware of the camera or microphone permissions either before this error happens.

`GetUserMedia - Meet needs access to the camera and microphone. Click the locked camera and microphone icon in your browser's address bar, before joining room` and  `NotAllowedError: The request is nt allowed by the user agent or the platform in the current context, possibly because the user denied permission.`
![IMG_8386](https://github.com/miroslavpejic85/mirotalkc2c/assets/13242557/f366a1e7-4ace-4039-a6ec-e520c18d53c2)

**Reproduce:**
- Grab an iOS device
- Firefox 
- c2c.mirotalk.com or any self-hosted setup w/ latest commits
- Enter Any Room name and username.
- See screenshot attached.

**Fix Ideas**
- I thought this would have been related to the /socket-io websocket not being properly forwarded. But that is not the case and websockets are setup as per the readme at `docs.mirotalk.com`
- MiroTalk P2P works fine on same iOS device with Firefox. There must be compatibility code not copied from P2P to C2C repository.
- 
**Notes:**
- These reproduction steps work fine on same iOS device with Safari app. Must be an issue with Firefox compatibility.
- MiroTalk P2P works fine on same iOS device with Firefox. There must be compatibility code not copied from P2P to C2C repository.
- Works fine on Android and Google Chrome app.

**Work around:**
- Use Safari app on iOS device

**Comment by miroslavpejic85** [comment]
Hello @torrswanson,

MiroTalk C2C has been successfully tested on Firefox for iOS in a [live demo](https://c2c.mirotalk.com), and it functions as intended. To utilize MiroTalk C2C, it is essential to grant access to your camera and microphone. Failure to do so will result in the following message: `The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

MiroTalk [P2P](https://p2p.mirotalk.com) and [SFU](https://sfu.mirotalk.com) works also without the camera and microphone, in contrast to C2C, which need it. 

Instead of creating an issue here, we kindly invite you to join us on our [official forum](https://discord.gg/rgGYfeYW3N). We have a dedicated `help-and-support` channel where you can find answers to many related queries without the need to raise issues. It's also a great platform for engaging with our community.

Thank you for considering this option.

**Comment by torrswanson** [comment]
Found the issue: It was in Apple Settings > Firefox > Microphone was disabled. Not in Firefox settings. Also found P2p.mirotalk.com was only ever working with camera access only. Subtle detail I missed.

![IMG_8387](https://github.com/miroslavpejic85/mirotalkc2c/assets/13242557/5d3ffe5e-db74-419c-9c3e-cc2e082b8162)
