### ISSUE TITLE
ngrok use on raspberry pi 

### ISSUE THREAD

**Issue by zoldaten** [miroslavpejic85/mirotalkc2c#13]
hi !
u tried ngrok to access local raspberry pi with grey IP. i seems connection established
![Screenshot_8](https://github.com/miroslavpejic85/mirotalkc2c/assets/29411817/aa58d19c-227f-499d-b4b2-d8f10c2da4f9)
 but i do not see any video-audio of a client. I see only myself in mirotalkc2c.
 
 In local net - everything is OK.
 
to check this out:
i followed steps https://docs.mirotalk.com/mirotalk-c2c/ngrok/
but got start it working like follows:
```
start ngrok:
ngrok http https://localhost:8080

in ~/mirotalkc2c
npm start 

start browser
libcamerify firefox -new-window https://localhost:8080/join?room=test&name=a
```

what is going wrong ?

**Comment by miroslavpejic85** [comment]
Hello @zoldaten,

Here's the revised set of instructions, as MiroTalk C2C handles Ngrok service internally:

1. Go to https://ngrok.com.
2. Sign up for a free account.
3. Copy your Ngrok Auth Token from https://dashboard.ngrok.com/get-started/your-authtoken.
4. Open the `.env` file in your MiroTalk C2C installation.
5. Add the following lines to the file:

```env
NGROK_ENABLED=true
NGROK_AUTH_TOKEN=YourNgrokAuthToken
```

Replace `YourNgrokAuthToken` with the token you copied.

6. Restart MiroTalk C2C. It automatically handles Ngrok service internally.

7. In the console log, find the three new URLs:

```js
[2023-12-17 19:01:41.072] [server] settings {
  // ...
  ngrokHome: 'https://xxxx-xxx-xxx-xx-xxx.ngrok-free.app',
  ngrokRoom: 'https://xxxx-xxx-xxx-xx-xxx.ngrok-free.app/?room=test',
  ngrokJoin: 'https://xxxx-xxx-xxx-xx-xxx.ngrok-free.app/join?room=test&name=test',
  //...
}
```

8. Share the desired URL outside to make your MiroTalk C2C reachable by anyone. MiroTalk C2C handles Ngrok service internally for you.

For help, support, or questions, please use our [community forum](https://discord.gg/rgGYfeYW3N) instead of opening issues here, as this platform is mainly for reporting confirmed bugs.

Thank you!
