### ISSUE TITLE
No way to configure empty iceServers

### ISSUE THREAD

**Issue by mlichvar** [miroslavpejic85/mirotalkc2c#5]
If my clients can connect directly to each other and I want to avoid using STUN/TURN servers, it seems iceServers needs to be set to an empty array. It would be nice if that was possible just by editing the `.env` file and not the source code. Currently it's hardcoded to contain a STUN and TURN server.

**Comment by miroslavpejic85** [comment]
Hello @mlichvar,

The `STUN` server `is mandatory` and can't be unset, which is why I put it forcing, in case someone doesn't set it at all. While the TURN is highly recommended, in case direct connection between peers is not possible, here You are right, as `TURN` is not mandatory, I made it `optional` in the last commit.

The STUN/TURN are configurable in the .env as well, but `STUN` must be set, if not, it use a google default one: `stun:stun.l.google.com:19302`. Without it, the `signaling server`, not knowing the peers IPs, is not able to connect them to each other.

You can install your own, following [this doc](https://github.com/miroslavpejic85/mirotalkc2c/blob/main/docs/coturn.md) I made.

This is the MiroTalk C2C logic.

![mirotalk-c2c-logic](https://user-images.githubusercontent.com/70838434/235223575-db7d8c3b-de9b-41f6-96e5-c85780f1a6e6.png)

- [What is STUN?](https://bloggeek.me/webrtcglossary/stun/)
- [What is TURN?](https://bloggeek.me/webrtcglossary/turn/)

For any doubts or questions, Join with us on [forum](https://discord.gg/rgGYfeYW3N), where you can also find many answers.
Thank you!

**Comment by mlichvar** [comment]
Well, it works for me with empty iceServers. This answer explains that it should use just the local addresses when no STUN/TURN is specified:
https://stackoverflow.com/questions/32301119/is-ice-necessary-for-client-server-webrtc-applications

I could run coturn on my router, but it doesn't seem to be useful in my case.

**Comment by miroslavpejic85** [comment]
If you use it `internally` to your `network`, you probably don't need the STUN either. Ok I'll make that optional too.

**Comment by mlichvar** [comment]
Thanks!

**Comment by miroslavpejic85** [comment]
You are welcome!
You can keep the Stun/Turn credentials and just enable or disable it, I added also two new params for that:
```ini
STUN_SERVER_ENABLED=false # true or false
TURN_SERVER_ENABLED=false # true or false
```
So, depending on the case, anyone can enable them or not ;)
